services:
  - type: web
    name: cted-coaches
    env: python
    plan: free
    branch: main
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: 3.12.3
    healthCheckPath: /login
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false